/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addFriends`; params?: Router.UnknownInputParams; } | { pathname: `/friends`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/homescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/ImageView/[URI]`, params: Router.UnknownInputParams & { URI: string | number; } } | { pathname: `/PDFView/[URI]`, params: Router.UnknownInputParams & { URI: string | number; } } | { pathname: `/profile/[userID]`, params: Router.UnknownInputParams & { userID: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/addFriends`; params?: Router.UnknownOutputParams; } | { pathname: `/friends`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/homescreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/ImageView/[URI]`, params: Router.UnknownOutputParams & { URI: string; } } | { pathname: `/PDFView/[URI]`, params: Router.UnknownOutputParams & { URI: string; } } | { pathname: `/profile/[userID]`, params: Router.UnknownOutputParams & { userID: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/addFriends${`?${string}` | `#${string}` | ''}` | `/friends${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs/homescreen${`?${string}` | `#${string}` | ''}` | `/tabs/notifications${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addFriends`; params?: Router.UnknownInputParams; } | { pathname: `/friends`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/homescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notifications`; params?: Router.UnknownInputParams; } | `/ImageView/${Router.SingleRoutePart<T>}` | `/PDFView/${Router.SingleRoutePart<T>}` | `/profile/${Router.SingleRoutePart<T>}` | { pathname: `/ImageView/[URI]`, params: Router.UnknownInputParams & { URI: string | number; } } | { pathname: `/PDFView/[URI]`, params: Router.UnknownInputParams & { URI: string | number; } } | { pathname: `/profile/[userID]`, params: Router.UnknownInputParams & { userID: string | number; } };
    }
  }
}
