ListenOn: "[::1]:9090"
LogFile: ""
DBAddress: "127.0.0.1:3306"
DBUser: "root"
DBPassword: "myVerySecretDBPassword1"
DBName: "hammerspace"
S3BucketName: "testing0"
TMPStorageDir: "......../Hammerspace/backend/tmp/"
S3Endpoint: "https://<account-id>.r2.cloudflarestorage.com"
S3AccessKeyID: "<AccessKey>"
S3AccessKeySecret: "<AccessKeySecret>"
LogLevel: "trace"
GINRelease: false